main:
  - name: Bio
    url: /
    weight: 10
  - name: Highlights
    url: /#highlights
    weight: 15
  - name: Experience
    url: experience/
    weight: 20
  - name: Timeline
    url: /timeline/
    weight: 21
  - name: Fun Fact
    url: /fun_fact/
    weight: 200
