# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'This is Triet Ho personal website.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: 'Triet Ho'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Triet Ho. All rights reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Disable foot note
show_powered_by: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
